version: 2.1
orbs:
  cypress: cypress-io/cypress@2
workflows:
  build:
    jobs:
      - cypress/install
      environment:
        CYPRESS_RECORD_KEY: 14ee76a6-6308-416c-b5a0-35d3ee4846be
      - cypress/run:
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 2
          group: 2 machines
